name: Build release candidate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

env:
  APK_PATH: app/build/outputs/apk/debug/app-debug.apk

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get release notes
        id: release-notes
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: "changelog_configuration.json"
          outputFile: "release_notes.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Show release notes
        run: echo ${{ steps.release-notes.outputs.changelog }}
